[default_session]
startup_command = "nvim +GoToFile"

[[session]]
name = "macmon"
path = "~/"
startup_command = "macmon"

[[session]]
name = "update"
path = "/tmp"
startup_command = "update"

[[session]]
name = "btop"
path = "/tmp"
startup_command = "btop"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "ll"

[[session]]
name = "Projects ğŸ’»"
path = "~/projects"
startup_command = "ll"

[[session]]
name = "dotfiles"
path = "~/projects/dotfiles"
startup_command = "nvim ."

[[session]]
name = "homelab"
path = "~/projects/homelab"
startup_command = "nvim ."

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"
